# Generated by Django 2.1.2 on 2018-10-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('songid', models.IntegerField(max_length=1000, primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=100)),
                ('songtitle', models.CharField(max_length=100)),
                ('albumtitle', models.CharField(max_length=100)),
                ('albumlogo', models.CharField(max_length=100)),
                ('releasedate', models.DateField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
