# Generated by Django 2.1.2 on 2018-10-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPlays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songhits', models.IntegerField()),
                ('songid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Songs')),
            ],
        ),
    ]
