# Generated by Django 2.1.2 on 2018-10-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20181018_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songdetails',
            name='is_favourite',
        ),
    ]
