# Generated by Django 2.1.2 on 2018-10-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20181020_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songdetails',
            name='songid',
        ),
        migrations.AlterField(
            model_name='songs',
            name='songid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SongDetails',
        ),
    ]
