# Generated by Django 2.1.2 on 2018-10-21 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0006_auto_20181021_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songhits', models.IntegerField()),
                ('songid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Songs')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
