# Generated by Django 2.1.2 on 2018-10-23 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0014_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videohits', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Videos')),
            ],
        ),
    ]
