# Generated by Django 2.1.2 on 2018-10-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20181024_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='username',
        ),
        migrations.RemoveField(
            model_name='videodetails',
            name='username',
        ),
    ]
