# Generated by Django 2.1.2 on 2018-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20181024_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='videodetails',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='songdetails',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
