# Generated by Django 2.1.2 on 2018-10-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20181024_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songdetails',
            name='approved_comment',
        ),
    ]
