# Generated by Django 2.1.2 on 2018-10-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_remove_songdetails_approved_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdetails',
            name='songid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.Songs'),
        ),
    ]
