# Generated by Django 2.1.2 on 2018-10-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_auto_20181025_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songdetails',
            old_name='songid',
            new_name='song_id',
        ),
    ]
