# Generated by Django 2.1.2 on 2018-10-25 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20181025_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodetails',
            name='videohits',
        ),
        migrations.AddField(
            model_name='videodetails',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videodetails',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='videodetails',
            name='videoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcomments', to='music.Videos'),
        ),
    ]
