# Generated by Django 2.1.2 on 2018-10-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20181025_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodetails',
            old_name='videoid',
            new_name='video_id',
        ),
    ]
